set noswapfile
set nobackup
set nocompatible
set number
set relativenumber
set numberwidth=1
set mouse=a
set showcmd
set ruler
set encoding=utf-8
set showmatch
set sw=4
set tabstop=4
set expandtab
set smarttab
set shiftwidth=4
set relativenumber
set laststatus=2
set clipboard=unnamedplus
set splitright
set splitbelow
set noshowmode

packadd! dracula
syntax enable
colorscheme dracula
