[env]
TERM = "xterm-256color"

[shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux"]

[colors.primary]
foreground = '#bbc2cf'
background ='#282c34'

[colors.cursor]
cursor = '#51afef'
text   = '#282c34'

[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#a9a1e1'
cyan    = '#46d9ff'
white   = '#bbc2cf'

[colors.bright]
black   = '#3f444a'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#da8548'
blue    = '#51afef'
magenta = '#a9a1e1'
cyan    = '#46d9ff'
white   = '#efefef'

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 1
